### ISSUE TITLE
Client handler for "Contain" is not working

### ISSUE THREAD

**Issue by flakeed** [deep-foundation/deepcase-app#260]
### Describe the bug

![image](https://github.com/deep-foundation/deepcase-app/assets/58123600/55a9b800-120b-4830-9997-f4056c5e720a)

```Unexpected token 'var'
SyntaxError: Unexpected token 'var'
    at new Function (<anonymous>)
    at eval (webpack-internal:///../deeplinks/imports/client-handler.js:20:33)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///../deeplinks/imports/client-handler.js:12:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///../deeplinks/imports/client-handler.js:8:12)
    at evalClientHandler (webpack-internal:///../deeplinks/imports/client-handler.js:17:12)
    at eval (webpack-internal:///../deepcase/imports/client-handler.js:321:122)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///../deepcase/imports/client-handler.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///../deepcase/imports/client-handler.js:70:12)
    at evalClientHandler (webpack-internal:///../deepcase/imports/client-handler.js:320:12)
    at ClientHandler._a (webpack-internal:///../deepcase/imports/client-handler.js:168:9)
    at commitHookEffectListMount (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24873:7)
    at commitPassiveMountEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:27034:3)
    at flushPassiveEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26979:14)
    at eval (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26764:9)
    at workLoop (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:533:21)```

### Expected Behavior

_No response_

### Current Behavior

_No response_

### Steps to reproduce

_No response_

### Environment

_No response_

**Comment by FreePhoenix888** [comment]
I am cheking deepcase client handlers and for some reason:
editorClientHandler preview is working
![image](https://github.com/deep-foundation/deepcase-app/assets/66206278/dea2cf16-be39-4e1b-a4f5-39c3ca233102)
queryClientHandler preview is not working
![image](https://github.com/deep-foundation/deepcase-app/assets/66206278/e9efac47-1807-4fff-8c1d-13542b1522f3)
stringClientHandler preview is not working
![image](https://github.com/deep-foundation/deepcase-app/assets/66206278/f63acdf2-be10-4095-b877-37f3c33dbc42)

Additional info:
![image](https://github.com/deep-foundation/deepcase-app/assets/66206278/c2b365ef-bae8-449f-bfc2-9814191e48fe)
There is no var keyword in this handler

**Comment by FreePhoenix888** [comment]
I have fixed this in deepcsae 0.0.99

**Comment by konard** [comment]
Actually fixed at https://github.com/deep-foundation/deeplinks/commit/16daede15610db67130ad30e30c30065addf86a6

**Comment by FreePhoenix888** [comment]
> Actually fixed at [deep-foundation/deeplinks@16daede](https://github.com/deep-foundation/deeplinks/commit/16daede15610db67130ad30e30c30065addf86a6)

What have my work was related to then? Why Am I unsigned? When I have updated handler link to link to TSX link (source code) instead of SyncTextFile (generated code) error was fixed
We both fixed it two ways

**Comment by konard** [comment]
@ivansglazunov @FreePhoenix888 as both of you did changes towards the solution, I will keep both of you assigned. Though it contradicts atomic responsibility principle.

In the future, @FreePhoenix888 please speak with @ivansglazunov first, when problem or feature is related to front-end. @ivansglazunov has a responsibility over front-end architecture. If we synchronized our perception earlier, we would decide the atomic responsibility for that issue.

We may use this issue as an example of how **not** to do in the future. So this case will be an exception to general practice.

**Comment by FreePhoenix888** [comment]
> @ivansglazunov @FreePhoenix888 as both of you did changes towards the solution, I will keep both of you assigned. Though it contradicts atomic responsibility principle.
> 
> In the future, @FreePhoenix888 please speak with @ivansglazunov first, when problem or feature is related to front-end. @ivansglazunov has a responsibility over front-end architecture. If we synchronized our perception earlier, we would decide the atomic responsibility for that issue.
> 
> We may use this issue as an example of how **not** to do in the future. So this case will be an exception to general practice.

I understand you, but ... It is not easy to contact @ivansglazunov and wait for his answer when a lot of people struggle cause of not working client handler. Also you as responsible for architecture said to me to do the changes I have made :)

**Comment by konard** [comment]
@FreePhoenix888 yes, and that was my mistake too. I should discuss it with @ivansglazunov next time.
