### ISSUE TITLE
Error when reusing ClientHandler `Manager` of package `chatgpt-azure`

### ISSUE THREAD

**Issue by TimaxHack** [deep-foundation/deepcase-app#303]
If you try to reuse the ClientHendler `Maneger` of the `chatgpt-azure` package, you may receive an error indicating that there are two `UsesApiKey` relationships:
```
rejected {
   name: 'Error',
   message: 'More than 1 links of type ##1156 are found',
   stack: 'Error: More than 1 links of type ##1156 are found\n' +
     ' at getTokenLink (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:366:13)\n' +
     ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
     ' at async eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:45:22)'
}
rejected {
   name: 'TypeError',
   message: "Cannot read properties of undefined (reading 'replace')",
   stack: "TypeError: Cannot read properties of undefined (reading 'replace')\n" +
     ' at eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:49:6)\n' +
     ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

If you delete any one `UsesApiKey`, there will be no error.

**Comment by TimaxHack** [comment]
Для исправления данной ошибки можно сделать предупреждение, что уже создана связь с типом `UsesApiKey`.

**Comment by FreePhoenix888** [comment]
I propose to add warning that UsesApiKey already exists and add ability to remove that link (with contain)

We can also check whether the same ApiKey already exists. This way we can check whether user tries to use the same api key again and show warning without insertimg extra-links
