### ISSUE TITLE
[0] FatalError: error TS5023: Unknown compiler option 'allowImportingTsExtensions'.

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#318]
```

> @deep-foundation/dev@0.0.21 gitpod-start
> export NEXT_PUBLIC_ENGINES=0; export NEXT_PUBLIC_HIDEPATH=1; export npm_config_yes=true; export JWT_SECRET="{\"type\":\"HS256\",\"key\":\"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R\"}" export MIGRATIONS_ID_TYPE_SQL=bigint; export MIGRATIONS_ID_TYPE_GQL=bigint; export MIGRATIONS_HASURA_PATH=$(echo $(gp url 8080) | awk -F[/:] '{print $4}'); export MIGRATIONS_HASURA_SSL=1; export MIGRATIONS_HASURA_SECRET=myadminsecretkey; export DEEPLINKS_HASURA_SECRET=myadminsecretkey;  export NEXT_PUBLIC_DEEPLINKS_SERVER=https://$(echo $(gp url 3007) | awk -F[/:] '{print $4}'); export NEXT_PUBLIC_GQL_PATH=$(echo $(gp url 3007) | awk -F[/:] '{print $4}')/api/gql; export NEXT_PUBLIC_GQL_SSL=1 DEEPLINKS_HASURA_PATH=localhost:8080; export DEEPLINKS_HASURA_SSL=0; export MIGRATIONS_DEEPLINKS_APP_URL=$(gp url 3007); export MIGRATIONS_DEEPLINKS_URL=$(gp url 3006); export DEEPLINKS_PUBLIC_URL=$(gp url 3006); export NEXT_PUBLIC_DEEPLINKS_URL=$(gp url 3006); export DOCKER_DEEPLINKS_URL=http://host.docker.internal:3006; export DEEPLINKS_ROUTE_HANDLERS_HOST=host.docker.internal; concurrently "npm run deepcase" "npm run deeplinks" "npm run gitpod-engine" "npm run sdk" "sleep 120 && npm run gitpod-hasura-reattach" "(cd packages/deeplinks && until [ -f ./warmup.js ]; do sleep 1; done && npm run warmup)" "(cd packages/deeplinks && npm run package:watch)" "(cd packages/deepcase && npm run package:watch)"

[0] 
[0] > @deep-foundation/dev@0.0.21 deepcase
[0] > (cd packages/deepcase-app && npm run dev -- -p 3007)
[0] 
[0] 
[0] > @deep-foundation/deepcase-app@0.1.0-beta.22 dev
[0] > next dev "-p" "3007"
[0] 
[0]   ▲ Next.js 14.2.2
[0]   - Local:        http://localhost:3007
[0]   - Environments: .env.development
[0] 
[0]  ✓ Starting...
[0]  ⚠ Invalid next.config.js options detected: 
[0]  ⚠     Invalid literal value, expected false at "i18n.localeDetection"
[0]  ⚠     Unrecognized key(s) in object: 'requiredNamespaces' at "i18n"
[0]  ⚠     Unrecognized key(s) in object: 'strictMode', 'allowImportingTsExtensions', 'webpack5', 'future'
[0]  ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
[0] FatalError: error TS5023: Unknown compiler option 'allowImportingTsExtensions'.
[0] 
[0]     at getTypeScriptConfiguration (/workspace/dev/node_modules/next/dist/lib/typescript/getTypeScriptConfiguration.js:49:19)
[0]     at writeConfigurationDefaults (/workspace/dev/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:185:117)
[0]     at verifyTypeScriptSetup (/workspace/dev/node_modules/next/dist/lib/verify-typescript-setup.js:121:74)
[0]     at async verifyTypeScript (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:112:26)
[0]     at async startWatcher (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:139:29)
[0]     at async setupDevBundler (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:775:20)
[0]     at async Span.traceAsyncFn (/workspace/dev/node_modules/next/dist/trace/trace.js:154:20)
[0]     at async initialize (/workspace/dev/node_modules/next/dist/server/lib/router-server.js:78:30)
[0]     at async Server.<anonymous> (/workspace/dev/node_modules/next/dist/server/lib/start-server.js:249:36)
[0] [?25h
[0] npm run deepcase exited with code 0
```

**Comment by konard** [comment]
Maybe this can help: https://stackoverflow.com/questions/76241919/how-can-i-fix-error-ts5023-throwed-by-adding-allowimportingtsextensions-in-tsc
