### ISSUE TITLE
FatalError: error TS5023: Unknown compiler option 'allowImportingTsExtensions'.

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepcase-app#322]
```
[0] FatalError: error TS5023: Unknown compiler option 'allowImportingTsExtensions'.
[0] 
[0]     at getTypeScriptConfiguration (/workspace/dev/node_modules/next/dist/lib/typescript/getTypeScriptConfiguration.js:49:19)
[0]     at writeConfigurationDefaults (/workspace/dev/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:185:117)
[0]     at verifyTypeScriptSetup (/workspace/dev/node_modules/next/dist/lib/verify-typescript-setup.js:121:74)
[0]     at async verifyTypeScript (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:112:26)
[0]     at async startWatcher (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:139:29)
[0]     at async setupDevBundler (/workspace/dev/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:775:20)
[0]     at async Span.traceAsyncFn (/workspace/dev/node_modules/next/dist/trace/trace.js:154:20)
[0]     at async initialize (/workspace/dev/node_modules/next/dist/server/lib/router-server.js:78:30)
[0]     at async Server.<anonymous> (/workspace/dev/node_modules/next/dist/server/lib/start-server.js:249:36)
[0] 
[0] npm run deepcase exited with code 0
```

**Comment by konard** [comment]
Regression of https://github.com/deep-foundation/deepcase-app/issues/318
